language: go
go:
  - 1.8
  - master
env:
  global:
  - DBNAME='pgproctest'
  - DBUSER='pgproctest'
  - DBPASS='pgproctest'
  - DBHOST='localhost'
services:
  - postgresql
addons:
  postgresql: '9.4'
before_install:
  - psql -c "create user $DBUSER password '$DBPASS'" -U postgres
  - psql -c "CREATE DATABASE $DBNAME WITH ENCODING='UTF8' owner=$DBUSER" -U postgres
  - PGPASSWORD=$DBPASS psql -h $DBHOST -U $DBUSER $DBNAME < tests.sql
  - go get github.com/mattn/goveralls
script:
  - go test -v -covermode=count -coverprofile=profile.cov
after_success:
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
